### ISSUE TITLE
how should I write the class code ?(for processing the data set so that it can be pytorch_geometric)

### ISSUE THREAD

**Issue by Shengyuan-Cai** [chrsmrrs/tudataset#2]
Analogous to the TUDataset， I have now understood and made the original format consistent with TUDataset, how should I write the class code ???(for processing the data set so that it can be pytorch_geometric)
I have prepared the raw data like this:

(1) XX_A.txt (m lines)
sparse (block diagonal) adjacency matrix for all graphs,
each line corresponds to (row, col) resp. (node_id, node_id)

(2) XX_graph_indicator.txt (n lines)
column vector of graph identifiers for all nodes of all graphs,
the value in the i-th line is the graph_id of the node with node_id i

(3) XX_graph_labels.txt (N lines)
class labels for all graphs in the dataset,
the value in the i-th line is the class label of the graph with graph_id i

(4) XX_node_attributes.txt (n lines)
matrix of node attributes,
the comma seperated values ​​in the i-th line is the attribute vector of the node with node_id i

**Comment by chrsmrrs** [comment]
Please lift your own weight.

**Comment by Shengyuan-Cai** [comment]
All right,Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chrsmrrs/tudataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 晚上8:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chrsmrrs/tudataset] how should I write the class code ?(for processing the data set so that it can be pytorch_geometric) (#2)





 
Please lift your own weight.
