### ISSUE TITLE
How to represent a molecule with the same format as TUDataset from a molecular SMILES?

### ISSUE THREAD

**Issue by hcji** [chrsmrrs/tudataset#3]
Hi,

I m trying to train a QSAR model some GNNs. But what I have is a list of molecular SMILES and the corresponding labels, for example:

```
x = ['CCCC', 'CCCO', 'CCCN' ...]
y = [1,1,0, ...]
```

Many of GNNs are taking your datasets as examples, which are preprocessed graph described by a list of files. But I did not find any way to convert to this format from molecular SMILES. Is there any function to convert molecular SMILES to the same format?

Thanks

**Comment by chrsmrrs** [comment]
No, we do not provide such a function, you need to write yourself.

**Comment by chrsmrrs** [comment]
Closed.

**Comment by chrsmrrs** [comment]
No, we do not provide such a function, you need to write it yourself.
